# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'README.md'

  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run --if-present build
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present format
      - run: |
          pnpm run dev &
          sleep 5
          xvfb-run pnpm run test

      - name: Upload diff
        if: failure()
        id: upload-diff
        env:
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: bash tools/upload_diff.sh

      - name: Create comment
        if: github.event_name == 'pull_request' && failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Visual regression test failed!**

            ${{ steps.upload-diff.outputs.diff-1 && format('![diff-1]({0})',steps.upload-diff.outputs.diff-1) }}
            ${{ steps.upload-diff.outputs.diff-2 && format('![diff-2]({0})',steps.upload-diff.outputs.diff-2) }}
            ${{ steps.upload-diff.outputs.diff-3 && format('![diff-3]({0})',steps.upload-diff.outputs.diff-3) }}
            ${{ steps.upload-diff.outputs.diff-4 && format('![diff-4]({0})',steps.upload-diff.outputs.diff-4) }}
